language: node_js
node_js:
  - "5.3"
env:
  - DIR=browserify
  - DIR=browserify_gulp
  - DIR=browserify_grunt
  - DIR=brunch
  - DIR=webpack
  - DIR=casperjs
  - DIR=cypress
  - DIR=mocha
  - DIR=jasmine
script:
  - ./travis-runner.sh
